MyLaps/MyLaps.Web/Controllers/EventController.cs
using System.Linq;
using System.Web.Mvc;
using MyLaps.Model;

namespace MyLaps.Web.Controllers
{
    public class EventController : Controller
    {
        public IEventProvider EventProvider { get; set; }

        public EventController (IEventProvider eventProvider)
        {
            EventProvider = eventProvider;
        }

        // GET: Event
        public ActionResult Index ()
        {
            return View();
        }
        public ActionResult Details (int id)
        {
            IEvent evt = EventProvider.GetEvent(id);
            if(evt == null)
            {
                return RedirectToAction("Index");
            }
            return View(evt);
        }
        [ChildActionOnly]
        public PartialViewResult LatestEvents ()
        {
            var lastEvents = EventProvider.GetEvents()
                                .OrderByDescending(e => e.Date)
                                .Take(5);
            return PartialView("_LatestEvents", lastEvents);
        }

    }
}

MyLaps/MyLaps.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace MyLaps.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index ()
        {
            return View();
        }
        public ActionResult About ()
        {
            return View();
        }
    }
}

MyLaps/MyLaps.Web/Controllers/RaceController.cs
using System.Web.Mvc;
using MyLaps.Model;

namespace MyLaps.Web.Controllers
{
    public class RaceController : Controller
    {
        IRaceProvider RaceProvider { get; set; }
        public RaceController (IRaceProvider raceProvider)
        {
            RaceProvider = raceProvider;
        }
        // GET: Race
        public ActionResult Details (int id)
        {
            IRace race = RaceProvider.GetRace(id);
            if(race == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View(race);
        }
    }
}

MyLaps/MyLaps.Web/Views/Event/Details.cshtml
@using R = MyLaps.Resources.Resources
@model MyLaps.Model.IEvent

@{
    ViewBag.Title = Model.Name;
}

<div class="row">
    <div class="row">
        <h1>@Model.Name</h1>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-4">
                    <strong>@R.Date:</strong>
                </div>
                <div class="col-md-4">
                    @Model.Date.ToLongDateString()
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <strong>@R.EventLocation:</strong>
                </div>
                <div class="col-md-4">
                    @Model.City, @Model.Country
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <strong>@R.EventType:</strong>
                </div>
                <div class="col-md-4">
                    @Model.Type
                </div>
            </div>
        </div>
        <div class="col-md-4 col-md-offset-2">
            <img style="max-height:300px;" src="@Model.LogoURL" alt="@R.EventLogo" />
        </div>
    </div>
</div>
<div class="row">
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#races" data-toggle="tab">@R.Races</a>
        </li>
        <li>
            <a href="#photos" data-toggle="tab">@R.Photos</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="races">
            <div>
                <table class="table">
                    <thead>
                        <tr>
                            <th class="">
                                @R.Name
                            </th>
                            <th>
                                @R.Distance
                            </th>
                            <th class="text-center">
                                @R.NumberOfParticipants
                            </th>
                            <th>

                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var race in Model.Races)
                        {
                            <tr>
                                <td @*class="col-md-3"*@>
                                    @race.Name
                                </td>
                                <td @*class="col-md-2"*@>
                                    @race.Distance meters
                                </td>
                                <td class="text-center">
                                    @*col-md-2*@
                                @race.Classifications.Count()
                            </td>
                            <td>
                                @Html.ActionLink(R.SeeMore, "Details", "Race", new { id = race.RaceID }, null)
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="tab-pane" id="photos">
            <div class="col-md-4 text-center">
                <img class="photos-tab-image" src="@Model.PhotoURL" />
            </div>
            <div class="col-md-4 text-center">
                <img class="photos-tab-image" src="@Model.LogoURL" />
            </div>
            <div class="col-md-4 text-center">
                <img class="photos-tab-image" src="@Model.SponsorURL" />
            </div>
        </div>
    </div>
</div>

MyLaps/MyLaps.Web/Views/Event/_LatestEvents.cshtml
@using R = MyLaps.Resources.Resources

@model IEnumerable<MyLaps.Model.IEvent>

@{
    if(Model == null || Model.Count() == 0)
    {
        <p>
            @R.NoEvents
        </p>
    }
    else
    {

        <ul>
            @foreach(var evt in Model.OrderByDescending(e => e.Date))
            {
                <li>
                    <a href="@Url.Action("Details", "Event", new { id = evt.EventID})">
                        @evt.Name @(evt.Date == default(DateTime) ? "" : " - " + evt.Date.ToLongDateString())
                    </a>
                </li>
            }
        </ul>
    }
}

MyLaps/MyLaps.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h2>About</h2>

<div class="row">
    <p>
        This assignment was developed by <a href="mailto:tiagofcmartins@gmail.com">Tiago Francisco Carreira Martins</a>
        for a job application in <a href="https://www.mylaps.com">MyLaps</a> at the 7th of December of 2015.
    </p>
    <p>
        The assignment code is available online, at <a href="https://bitbucket.org/TiagoPT/mylaps-assignment">Bitbucket</a>.
    </p>
</div>

MyLaps/MyLaps.Web/Views/Home/Index.cshtml
@using R = MyLaps.Resources.Resources

<div class="page-header">
    <h2>@R.Greeting</h2>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div id="carousel-example-generic" class="carousel slide carousel-slider" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner text-center" role="listbox">
                <div class="item active">
                    <img class="carousel-image text-center" style="padding-top:85px;" src="https://upload.wikimedia.org/wikipedia/en/5/52/Logo_for_MYLAPS_Sports_Timing.jpg" alt="Application Logo">
                </div>
                <div class="item text-center">
                    <img class="carousel-image" src="https://i815.photobucket.com/albums/zz74/victor_the_crab/Classic%20Gas%20Station%20Logos/MarathonLogo.png" alt=" Event Sponsor">
                </div>
                <div class="item ">
                    <img class="carousel-image" src="https://upload.wikimedia.org/wikipedia/commons/1/1e/Orlen_Warsaw_Marathon_2014_al._KEN.JPG" alt="Event Photo">
                </div>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

<div class="row">
    <h3>
        @R.LatestEvents
    </h3>
    <div class="row">
        @Html.Action("LatestEvents", "Event")
    </div>
</div>

MyLaps/MyLaps.Web/Views/Race/Details.cshtml
@using R = MyLaps.Resources.Resources

@model MyLaps.Model.IRace
@{
    ViewBag.Title = Model.Name;
    var athletes = Model.Classifications.OrderBy(c => c.Rank);
}
<div class="row">
    <h1>@Model.Name</h1>
    <div class="row" style="padding-top: 20px; padding-bottom:20px; padding-left: 25px;">
        <div class="row">
            <div class="col-md-2">
                <strong>@R.NumberOfParticipants:</strong>
            </div>
            <div class="col-md-2">
                @athletes.Count()
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <strong>@(R.Distance)(m):</strong>
            </div>
            <div class="col-md-2">
                @Model.Distance
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <table class="table">
            <thead>
                <tr>
                    <th class="col-md-2 text-center">
                        <strong>@R.Position</strong>
                    </th>
                    <th class="col-md-5 text-center">
                        <strong>@R.BibNumber</strong>
                    </th>
                    <th class="col-md-5 text-right">
                        <strong>@R.TotalTime</strong>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var athlete in athletes)
                {
                    athlete.Splits = athlete.Splits.OrderBy(s => s.Distance);
                <tr onclick="toggleSplit(@athlete.BibNumber)">
                    <td class="col-md-2 text-center">
                        @athlete.Rank
                    </td>
                    <td class="col-md-5 text-center">
                        @athlete.BibNumber
                    </td>
                    <td class="col-md-5 text-right">
                        @athlete.Splits.Last().Time
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        @foreach(var athlete in athletes)
        {
            int idx = 1;
        <div class="row hidden" id="splits@(athlete.BibNumber)">
            <h5>
                @string.Format(R.SplitTimesTitle, athlete.BibNumber)
            </h5>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @R.SplitNumber
                        </th>
                        <th>
                            @R.Name
                        </th>
                        <th>
                            @R.Distance (m)
                        </th>
                        <th>
                            @R.SplitTime
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var split in athlete.Splits)
                        {
                        <tr>
                            <td>
                                @(idx++)
                            </td>
                            <td>
                                @split.Name
                            </td>
                            <td>
                                @split.Distance
                            </td>
                            <td class="text-right">
                                @split.Time
                            </td>
                        </tr>
                        }
                </tbody>
            </table>
        </div>
        }
    </div>
</div>
<script type="text/javascript">
    var lastBib = -1;
    function toggleSplit(bibID) {
        console.log('toggleSplit');
        if (lastBib != -1) {
            $('#splits' + lastBib).toggleClass("hidden");
        }
        if (lastBib != bibID){
            $('#splits' + bibID).toggleClass("hidden");
        }
        lastBib = lastBib == bibID ? -1 : bibID;
    }
</script>

MyLaps/MyLaps.Web/Views/Shared/_Layout.cshtml
@using R = MyLaps.Resources.Resources

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@(string.IsNullOrEmpty(ViewBag.Title) ? "" : ViewBag.Title + " - ") MyLaps Assignment</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(R.ApplicationName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>
    <script src="~/Scripts/jquery-2.1.4.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>